### PR TITLE
Update Java SDK to 1.12.597 to benefit from IMDSv2

### PR DESCRIPTION
**Pull request by samidalouche**
Is this project still maintained? 

Here is a simple dependency update for the AWS Java SDK. There are a couple fixes we are interested in, and everyone would probably benefit from the upgrade.

### CODE REVIEW

**Comment by samidalouche** [comment]
Thanks for merging. Would you mind publishing a new release with the fix?

The reason I ask is because since we use s3 as a repository, there is a bit of a chicken-and-egg problem with publishing `fm-sbt-s3-resolver` to our repo.

Thanks a lot!

**Comment by tpunder** [comment]
It's going out now :)

**Comment by tpunder** [comment]
@samidalouche Looks like it is sync'd to maven central now: https://repo1.maven.org/maven2/com/frugalmechanic/fm-sbt-s3-resolver_2.12_1.0/0.22.0/

**Comment by samidalouche** [comment]
Amazing! Thanks again!

**Pull request merged**
