### PR TITLE
allow specifying bucket ACL policy on upload

### PR DESCRIPTION
**Pull request by kevin-brendle-lark**
adding settings key for a map of bucket name to ACL. update upload.putImpl to optionally allow multiple customizations to the PutObjectRequest

### CODE REVIEW

**Comment by kevin-brendle-lark** [comment]
Hey @tpunder, I am using your package as part of some data engineering activities and it has worked great for using s3 as a maven source. However, I ran into an S3 bucket that requires ACL to be set on the put requests which prompted this PR. 

Overall, functionally everything is backwards compatible and this update is being used to perform uploads with this s3 restriction. I was able to preserve the existing code flow while adding this optional argument to the s3 upload which will also serve to allow further customizations.

Is this something that you think we could work in? I'm happy to make updates to better align towards your vision for the project

**Comment by tpunder** [comment]
@kevin-brendle-lark Merged and published as version `0.21.0`. Sorry for the delay! I meant to take a look at this when it came in last week but then got sidetracked.

**Comment by kevin-brendle-lark** [comment]
> @kevin-brendle-lark Merged and published as version `0.21.0`. Sorry for the delay! I meant to take a look at this when it came in last week but then got sidetracked.

no problem. I know how it goes, that's why i figured a poke might be good. thank you!

**Comment by tpunder** [comment]
Yup, thanks for the poke 😄 

Maven central sync should kick in soon (usually 10 mins or so) for `0.21.0`

**Pull request merged**
