### PR TITLE
adding environment variable to allow for encrypted uploads to S3

### PR DESCRIPTION
**Pull request by etspaceman**

### CODE REVIEW

**Comment by etspaceman** [comment]
This simply introduces an environment variable ENCRYPT_AWS_SBT_UPLOADS, which can be set to TRUE or FALSE. I'm sure there's more elegant ways to work with this code-base, I'm all ears as to how you'd prefer to approach this.

**Comment by er1c** [comment]
It might be interesting to add these to the various config files too, so it's not just an environment variable...albeit that probably requires a more complicated code change

**Comment by tpunder** [comment]
This is also being worked on in https://github.com/frugalmechanic/fm-sbt-s3-resolver/pull/28 by automatically enabling SSE if the bucket policy requires it.

**Comment by tpunder** [comment]
Hopefully #28 solved this.

**Pull request closed without merging**
